# Generated by Django 4.0.3 on 2022-05-12 02:11

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_article_article_pic_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(default='article/article.png', null=True, upload_to=post.models.article_directory_path, verbose_name='Image'),
        ),
    ]
