# Generated by Django 4.0.3 on 2022-05-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_article_article_hashtag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='interset',
            field=models.ManyToManyField(to='post.interest'),
        ),
    ]
