# Generated by Django 4.0.3 on 2022-05-11 23:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_interset'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='users/user.png', null=True, upload_to=users.models.user_directory_path, verbose_name='Image'),
        ),
    ]
